### PR TITLE
Automation jobs

### PR DESCRIPTION
**Pull request by lakhassane**

### CODE REVIEW

**Comment by aleksa-krolls** [comment]
@lakhassane what is this issue?

**Comment by taylordowns2000** [comment]
@lakhassane , is this the required change so that there's only one OpenFn `job` per Kobo `formId`? Is there something specific that isn't working as desired, or is this simply a general PR review request? I wasn't sure from your message on Friday if there's something specific that I should be looking into here.

If everything is working in the tests locally, no worries to shift testing to OpenFn.org now.

**Comment by lakhassane** [comment]
@aleksa-krolls it was to enhance how we handle repeat groups job creation on openfn.org. I had to add a `delete` statement before bulk inserting repeat groups.

@taylordowns2000 it was a classical PR for feedbacks before merging on `master`. Locally everything is working as intended.

**Review by taylordowns2000 — APPROVED** [review]
:+1:

**Pull request closed without merging**
